# Perfil de desarrollo (tu PC local con MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/vinoteca?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=Claude
spring.datasource.password=Magui420
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=8083

# CORS para Vite (dev)
app.cors.allowed-origins=http://localhost:5175
