# ====================================================
# Perfil ACTIVO por defecto = dev (tu PC con MySQL local)
# Para producción se setea SPRING_PROFILES_ACTIVE=prod (Railway lo hace solo si está en variables)
# ====================================================
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Config común
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=America/Argentina/Buenos_Aires
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
